# Generated by Django 5.0.7 on 2024-07-20 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StoicQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.TextField()),
                ('philosopher', models.CharField(max_length=100)),
                ('explanation', models.TextField()),
            ],
        ),
    ]
